version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
  mysql:
    image: mysql:8-oracle
    container_name: db_container
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bemyplan