version: '3'
services:
  mysql:
    image: mysql:8.0.32
    container_name: db_container
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: {db_passoword}
      MYSQL_DATABASE: {db_name}
