server:
  port: 8080

#max file and request size
spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 201MB
  response:
    black-list:
      - "/"
      - "/v*/api-docs"
      - "/swagger-resources/**"
      - "/swagger-ui.html"
      - "/webjars/**"
      - "/swagger/**"
    success:
      code: 200
      msg: SUCCESS
    exceptions:
      NotFoundException:
        code: 404
        msg: '존재하지 않습니다'
        type: 'com.deploy.bemyplan.common.exception.model.NotFoundException'
      ConflictException:
        code: 409
        msg: '이미 존재합니다'
        type: 'com.deploy.bemyplan.common.exception.model.ConflictException'
      ValidationException:
        code: 400
        msg: '잘못된 요청입니다'
        type: 'com.deploy.bemyplan.common.exception.model.ValidationException'
      NotAuthException:
        code: 400
        msg: '잘못된 요청입니다'
        type: 'com.deploy.bemyplan.config.auth.NotAuthException'
      UniqueViolationException:
        code: 400
        msg: '중복된 요청입니다'
        type: 'org.springframework.dao.DataIntegrityViolationException'
logging:
  slack:
    webhook-uri: {slack_url}
    config: classpath:logback-spring.xml
s3:
  profile: prod
