server:
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://bemyplan-dev-mysql.c3p7kjpj7cej.ap-northeast-2.rds.amazonaws.com:3306/bemyplan?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: bemyplan_dev
    password: bemyplan_pwd

  redis:
    host: bemyplan-deploy-redis.tbtn3b.ng.0001.apn2.cache.amazonaws.com
    port: 6379

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    generate-ddl: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace