spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://bemyplan-dev-mysql.c3p7kjpj7cej.ap-northeast-2.rds.amazonaws.com:3306/bemyplan_dev?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: bemyplan_dev
    password: bemyplan_pwd
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    generate-ddl: true
  redis:
    host: localhost
    port: 6379


logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace